[project]
name = "igknite"
version = "2025.3.3"
description = "Unified, swiss-grade moderation & music bot for Discord"
readme = "README.md"
requires-python = ">=3.13"
packages = [ { include = "igknite" } ]
dependencies = [
    "async-timeout>=5.0.1",
    "click>=8.3.2",
    "disnake[voice]>=2.12.0",
    "python-decouple>=3.8",
    "spotipy>=2.26.0",
    "yt-dlp>=2025.2.19",
]

[project.scripts]
igknite = "igknite.main:cli"

[tool.ruff]
target-version = "py313"
exclude = [".venv"]

[tool.ruff.format]
quote-style = "single"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
